### ISSUE TITLE
authkestra-providers fails to compile with only the `github` or `google` feature

### ISSUE THREAD

**Issue by marcjazz** [marcjazz/authly-rs#321]
## Summary

`authkestra-providers` declares `urlencoding` as an optional dependency enabled **only** by the `discord` feature, but uses it in the macro that generates **every** provider. So depending on the crate with just `github`, or just `google`, fails to compile inside the dependency.

## Reproducing

```toml
[dependencies]
authkestra-providers = { version = "0.8.0", features = ["github"] }
```

```
error[E0433]: cannot find module or crate `urlencoding`
   --> authkestra-providers-0.8.0/src/macros.rs:108:36
    |
108 |     redirect_uri = urlencoding::encode(&self.redirect_uri),
    |                    ^^^^^^^^^^^ use of unresolved module or unlinked crate `urlencoding`

error[E0433]: cannot find module or crate `urlencoding`
   --> authkestra-providers-0.8.0/src/macros.rs:110:35
```

Same with `features = ["google"]`. Adding `discord` makes it compile.

## Why

`crates/authkestra-providers/Cargo.toml`:

```toml
[features]
default = ["rustls-aws-lc-rs"]
discord = ["urlencoding"]
github = []
google = []
```

`urlencoding` is behind `discord`, but `macros.rs` uses it unconditionally — it is in `define_oauth_provider!`, which generates GitHub and Google too.

The workspace itself never hits this: everything in-tree that uses the crate enables all three providers at once, so `urlencoding` is always on.

## Impact

The `github` and `google` features are individually unusable. Anyone wanting a single provider has to enable `discord` as well, and nothing says so — the error appears inside a dependency, which is a confusing place to land.

Found while generating starter projects: a project selecting only GitHub sign-in does not build.

## Suggested fix

`urlencoding` is used by all providers, so make it unconditional:

```toml
[dependencies]
urlencoding = "2"      # not optional

[features]
discord = []
```

Alternatively, if the intent is to keep it optional, gate the macro's use of it — but since every generated provider percent-encodes its redirect URI and scopes, unconditional looks right.

Either way a CI check that each provider feature builds on its own would catch this class of thing:

```sh
for f in github google discord; do
  cargo check -p authkestra-providers --no-default-features --features "$f,rustls-aws-lc-rs" || exit 1
done
```

## Workaround meanwhile

The playground's starter-kit generator adds `discord` to the feature list whenever any provider is selected, with a comment pointing here. It costs an unused provider in the dependency graph and nothing else.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
